### ISSUE TITLE
Community Application

### ISSUE THREAD

**Issue by StephenCoady** [aerogear/graphql-home#6]
I think we should create a community application for Offix in React which uses a real-life schema instead of the to do app. The benefit is we hit more edge cases in development and it is easier for other developers to on-board and start using Offix.

**Comment by wtrocki** [comment]
Agreed. Currently, we have 2 spikes:

https://github.com/darahayes/offix-example-react/
https://github.com/wtrocki/offix-react-native-sample
https://github.com/aerogear/chat-app

**Comment by wtrocki** [comment]
Showcase is now using directly offix-boost. We have react native app as well

**Comment by wtrocki** [comment]
ping @darahayes
